stages:
 - build

build-ubuntu:
  parallel:
    matrix:
      - UBUNTU_VERSION: [ "focal", "jammy", "noble", "resolute" ]
  stage: build
  image: ${CI_REGISTRY_IMAGE}/ubuntu:${UBUNTU_VERSION}
  script:
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - ctest -V

build-ubuntu-fpm:
  parallel:
    matrix:
      - UBUNTU_VERSION: [ "focal", "jammy", "noble", "resolute" ]
  stage: build
  image: ${CI_REGISTRY_IMAGE}/ubuntu:${UBUNTU_VERSION}
  script:
    - fpm build
    - fpm test

build-almalinux:
  tags:
    - haswell
  parallel:
    matrix:
      - ALMA_VERSION: ["8", "9", "10" ]
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/almalinux:${ALMA_VERSION}
  script:
    - dnf install -y blas-devel lapack-devel
    - if [ ${ALMA_VERSION} -eq 9 ]; then (cd /usr/lib64/; ln -sf libblas.so.3.9.0 libblas.so.3; ln -sf liblapack.so.3.9.0 liblapack.so.3 ); fi
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - ctest -V

build-fedora:
  parallel:
    matrix:
      - FEDORA_VERSION: ["40", "41", "42" ]
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/fedora:${FEDORA_VERSION}
  script:
    - dnf install -y flexiblas-devel
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - ctest -V

build-aocc:
  parallel:
    matrix:
      - AOCC_VERSION: [ "5.1.0", "5.2.0" ]
  stage: build
  needs: []
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/aocc-compiler/noble:${AOCC_VERSION}
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
      # We do not run the test with AOCC since the compiler produces invalid results
      # - ctest -V

build-intel:
  parallel:
    matrix:
      - INTEL_VERSION: [ "2024", "2025", "2026" ]
  stage: build
  needs: []
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/intel-compiler/noble:${INTEL_VERSION}
  script:
    - mkdir -p build
    - cd build
    - CC=icx FC=ifx cmake ../ -DDEBUG=ON -DBLA_VENDOR=Intel10_64lp
    - make
    - ctest -V



coverage:
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/ubuntu:noble
  stage: build
  needs: []
  script:
    - apt update && apt-get install --yes --no-install-recommends lcov gcovr libopenblas-dev libblas-dev liblapack-dev
    - cmake -S . -B build-dir -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=ON
    - cmake --build build-dir
    - cd build-dir
    - make
    - OMP_NUM_THREADS=1 make test
    - make gcov
    - gcovr -r ..
  coverage: '/^TOTAL.*\s+(\d+\%)$/'


cross-win32:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:focal
  script:
    - bash ./tools/ci/cross-win32.sh

cross-win64:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:focal
  script:
    - bash ./tools/ci/cross-win64.sh

cross-win32-jammy:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:jammy
  script:
    - bash ./tools/ci/cross-win32.sh

cross-win64-jammy:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:jammy
  script:
    - bash ./tools/ci/cross-win64.sh


