stages:
 - build

build-ubuntu:
  parallel:
    matrix:
      - UBUNTU_VERSION: [ "xenial", "bionic", "xenial", "focal", "jammy", "noble" ]
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/ubuntu:${UBUNTU_VERSION}
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test


build-almalinux:
  tags:
    - haswell
  parallel:
    matrix:
      - ALMA_VERSION: ["8", "9", "10" ]
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/almalinux:${ALMA_VERSION}
  script:
    - dnf install -y blas-devel lapack-devel
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test

cross-win32:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:focal
  script:
    - bash ./tools/ci/cross-win32.sh

cross-win64:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:focal
  script:
    - bash ./tools/ci/cross-win64.sh

cross-win32-jammy:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:jammy
  script:
    - bash ./tools/ci/cross-win32.sh

cross-win64-jammy:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:jammy
  script:
    - bash ./tools/ci/cross-win64.sh


