stages:
 - build

ubuntu1604:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/ubuntu:xenial
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test

ubuntu1804:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/ubuntu:bionic
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test

ubuntu2004:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/ubuntu:focal
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test

ubuntu2204:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/ubuntu:jammy
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test


ubuntu2204:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/ubuntu:noble
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test

centos8:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/centos:8-base
  script:
    - yum install -y blas-devel lapack-devel
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON
    - make
    - make test

cross-win32:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:focal
  script:
    - bash ./tools/ci/cross-win32.sh

cross-win64:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:focal
  script:
    - bash ./tools/ci/cross-win64.sh

cross-win32-jammy:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:jammy
  script:
    - bash ./tools/ci/cross-win32.sh

cross-win64-jammy:
  stage: build
  image: gitlab.mpi-magdeburg.mpg.de/ci-images/minimal/mingw:jammy
  script:
    - bash ./tools/ci/cross-win64.sh

