#ifndef QRUPDATE_EXPORT_H
#define QRUPDATE_EXPORT_H

#  define QRUPDATE_EXPORT
#  define QRUPDATE_NO_EXPORT
#  define QRUPDATE_DEPRECATED
#  define QRUPDATE_DEPRECATED_EXPORT QRUPDATE_EXPORT QRUPDATE_DEPRECATED
#  define QRUPDATE_DEPRECATED_NO_EXPORT QRUPDATE_NO_EXPORT QRUPDATE_DEPRECATED

#endif /* QRUPDATE_EXPORT_H */
