/*
 * C interface test for input validation (qrupdate_xerror) for all qrupdate functions.
 * Port of test_qrupdate_validation.f90
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "qrupdate.h"
#include "qrupdate_fortran_mangle.h"
#include "qrupdate_fortran_types.h"

extern void ctest_set_handler(void);
extern void ctest_reset_state(void);
extern int ctest_get_xerbla_called(void);
extern int ctest_get_last_info(void);
extern int ctest_srname_eq(const char *expected);

#define N 5

static int fails = 0;

static void check_error(const char *name, int expected_info) {
    if (!ctest_get_xerbla_called()) {
        printf("FAIL: xerbla not called for %s\n", name);
        fails++;
    } else if (!ctest_srname_eq(name)) {
        printf("FAIL: expected srname \"%s\"\n", name);
        fails++;
    } else if (ctest_get_last_info() != expected_info) {
        printf("FAIL: expected info=%d for %s but got info=%d\n", expected_info, name, ctest_get_last_info());
        fails++;
    } else {
        printf("PASS: %s info=%d\n", name, ctest_get_last_info());
    }
}

#define CHECK_ERROR(name, expected) check_error(name, expected)

int main(void) {
    qrupdate_fortran_int_t n = N;
    qrupdate_fortran_int_t info;

    /* Allocate zeroed arrays */
    float R_s[N*N], u_s[N], w_s[N];
    double R_d[N*N], u_d[N], w_d[N];
    float _Complex R_c[N*N], u_c[N];
    double _Complex R_z[N*N], u_z[N];
    float Q_s[N*N], c_s[N-1], s_s[N-1], rhs_s[N];
    double Q_d[N*N], c_d[N-1], s_d[N-1], rhs_d[N];
    float _Complex Q_c[N*N], rhs_c[N];
    double _Complex Q_z[N*N], rhs_z[N];
    float c_c[N-1], c_z[N-1];
    float _Complex s_c[N-1];
    double _Complex s_z[N-1];
    float L_s[N*N], v_s[N], wv_s[N];
    double L_d[N*N], v_d[N], wv_d[N];
    float _Complex L_c[N*N], v_c[N], wv_c[N];
    double _Complex L_z[N*N], v_z[N], wv_z[N];
    qrupdate_fortran_int_t p_s[N], p_c_int[N], p_d[N], p_z_int[N];
    float x_s[N];
    double x_d[N];
    float _Complex x_c[N];
    double _Complex x_z[N];
    float rw_float[N];
    double rw_double[N];
    char dir;

    memset(R_s, 0, sizeof(R_s)); memset(u_s, 0, sizeof(u_s)); memset(w_s, 0, sizeof(w_s));
    memset(R_d, 0, sizeof(R_d)); memset(u_d, 0, sizeof(u_d)); memset(w_d, 0, sizeof(w_d));
    memset(R_c, 0, sizeof(R_c)); memset(u_c, 0, sizeof(u_c));
    memset(R_z, 0, sizeof(R_z)); memset(u_z, 0, sizeof(u_z));
    memset(Q_s, 0, sizeof(Q_s)); memset(c_s, 0, sizeof(c_s));
    memset(s_s, 0, sizeof(s_s)); memset(rhs_s, 0, sizeof(rhs_s));
    memset(Q_d, 0, sizeof(Q_d)); memset(c_d, 0, sizeof(c_d));
    memset(s_d, 0, sizeof(s_d)); memset(rhs_d, 0, sizeof(rhs_d));
    memset(Q_c, 0, sizeof(Q_c)); memset(c_c, 0, sizeof(c_c));
    memset(s_c, 0, sizeof(s_c)); memset(rhs_c, 0, sizeof(rhs_c));
    memset(Q_z, 0, sizeof(Q_z)); memset(c_z, 0, sizeof(c_z));
    memset(s_z, 0, sizeof(s_z)); memset(rhs_z, 0, sizeof(rhs_z));
    memset(L_s, 0, sizeof(L_s)); memset(v_s, 0, sizeof(v_s)); memset(wv_s, 0, sizeof(wv_s));
    memset(L_d, 0, sizeof(L_d)); memset(v_d, 0, sizeof(v_d)); memset(wv_d, 0, sizeof(wv_d));
    memset(L_c, 0, sizeof(L_c)); memset(v_c, 0, sizeof(v_c)); memset(wv_c, 0, sizeof(wv_c));
    memset(L_z, 0, sizeof(L_z)); memset(v_z, 0, sizeof(v_z)); memset(wv_z, 0, sizeof(wv_z));
    memset(p_s, 0, sizeof(p_s)); memset(p_c_int, 0, sizeof(p_c_int));
    memset(p_d, 0, sizeof(p_d)); memset(p_z_int, 0, sizeof(p_z_int));
    memset(x_s, 0, sizeof(x_s)); memset(x_d, 0, sizeof(x_d));
    memset(x_c, 0, sizeof(x_c)); memset(x_z, 0, sizeof(x_z));
    memset(rw_float, 0, sizeof(rw_float)); memset(rw_double, 0, sizeof(rw_double));

    printf("Testing input validation for all qrupdate functions...\n");
    ctest_set_handler();

    /* ====== Cholesky downdate ====== */
    ctest_reset_state();
    qrupdate_sch1dn(-1, R_s, n, u_s, rw_float, &info);
    CHECK_ERROR("SCH1DN", 1);
    ctest_reset_state();
    qrupdate_sch1dn(n, R_s, n-1, u_s, rw_float, &info);
    CHECK_ERROR("SCH1DN", 3);
    ctest_reset_state();
    qrupdate_dch1dn(-1, R_d, n, u_d, rw_double, &info);
    CHECK_ERROR("DCH1DN", 1);
    ctest_reset_state();
    qrupdate_dch1dn(n, R_d, n-1, u_d, rw_double, &info);
    CHECK_ERROR("DCH1DN", 3);
    ctest_reset_state();
    qrupdate_cch1dn(-1, R_c, n, u_c, rw_float, &info);
    CHECK_ERROR("CCH1DN", 1);
    ctest_reset_state();
    qrupdate_cch1dn(n, R_c, n-1, u_c, rw_float, &info);
    CHECK_ERROR("CCH1DN", 3);
    ctest_reset_state();
    qrupdate_zch1dn(-1, R_z, n, u_z, rw_double, &info);
    CHECK_ERROR("ZCH1DN", 1);
    ctest_reset_state();
    qrupdate_zch1dn(n, R_z, n-1, u_z, rw_double, &info);
    CHECK_ERROR("ZCH1DN", 3);

    /* ====== Cholesky delete ====== */
    ctest_reset_state();
    qrupdate_schdex(-1, R_s, n, 1, w_s);
    CHECK_ERROR("SCHDEX", 1);
    ctest_reset_state();
    qrupdate_schdex(n, R_s, n, 0, w_s);
    CHECK_ERROR("SCHDEX", 4);
    ctest_reset_state();
    qrupdate_dchdex(-1, R_d, n, 1, w_d);
    CHECK_ERROR("DCHDEX", 1);
    ctest_reset_state();
    qrupdate_dchdex(n, R_d, n, 0, w_d);
    CHECK_ERROR("DCHDEX", 4);
    ctest_reset_state();
    qrupdate_cchdex(-1, R_c, n, 1, rw_float);
    CHECK_ERROR("CCHDEX", 1);
    ctest_reset_state();
    qrupdate_cchdex(n, R_c, n, 0, rw_float);
    CHECK_ERROR("CCHDEX", 4);
    ctest_reset_state();
    qrupdate_zchdex(-1, R_z, n, 1, rw_double);
    CHECK_ERROR("ZCHDEX", 1);
    ctest_reset_state();
    qrupdate_zchdex(n, R_z, n, 0, rw_double);
    CHECK_ERROR("ZCHDEX", 4);

    /* ====== Cholesky insert ====== */
    ctest_reset_state();
    qrupdate_schinx(-1, R_s, n, 1, u_s, w_s, &info);
    CHECK_ERROR("SCHINX", -1);
    ctest_reset_state();
    qrupdate_schinx(n, R_s, n, 0, u_s, w_s, &info);
    CHECK_ERROR("SCHINX", -4);
    ctest_reset_state();
    qrupdate_dchinx(-1, R_d, n, 1, u_d, w_d, &info);
    CHECK_ERROR("DCHINX", 1);
    ctest_reset_state();
    qrupdate_dchinx(n, R_d, n, 0, u_d, w_d, &info);
    CHECK_ERROR("DCHINX", 4);
    ctest_reset_state();
    qrupdate_cchinx(-1, R_c, n, 1, u_c, rw_float, &info);
    CHECK_ERROR("CCHINX", -1);
    ctest_reset_state();
    qrupdate_cchinx(n, R_c, n, 0, u_c, rw_float, &info);
    CHECK_ERROR("CCHINX", -4);
    ctest_reset_state();
    qrupdate_zchinx(-1, R_z, n, 1, u_z, rw_double, &info);
    CHECK_ERROR("ZCHINX", -1);
    ctest_reset_state();
    qrupdate_zchinx(n, R_z, n, 0, u_z, rw_double, &info);
    CHECK_ERROR("ZCHINX", -4);

    /* ====== Cholesky shift ====== */
    ctest_reset_state();
    qrupdate_schshx(-1, R_s, n, 1, 1, w_s);
    CHECK_ERROR("SCHSHX", 1);
    ctest_reset_state();
    qrupdate_schshx(n, R_s, n, 0, 1, w_s);
    CHECK_ERROR("SCHSHX", 4);
    ctest_reset_state();
    qrupdate_schshx(n, R_s, n, 1, 0, w_s);
    CHECK_ERROR("SCHSHX", 5);
    ctest_reset_state();
    qrupdate_dchshx(-1, R_d, n, 1, 1, w_d);
    CHECK_ERROR("DCHSHX", 1);
    ctest_reset_state();
    qrupdate_dchshx(n, R_d, n, 0, 1, w_d);
    CHECK_ERROR("DCHSHX", 4);
    ctest_reset_state();
    qrupdate_dchshx(n, R_d, n, 1, 0, w_d);
    CHECK_ERROR("DCHSHX", 5);
    ctest_reset_state();
    qrupdate_cchshx(-1, R_c, n, 1, 1, wv_c, rw_float);
    CHECK_ERROR("CCHSHX", 1);
    ctest_reset_state();
    qrupdate_cchshx(n, R_c, n, 0, 1, wv_c, rw_float);
    CHECK_ERROR("CCHSHX", 4);
    ctest_reset_state();
    qrupdate_cchshx(n, R_c, n, 1, 0, wv_c, rw_float);
    CHECK_ERROR("CCHSHX", 5);
    ctest_reset_state();
    qrupdate_zchshx(-1, R_z, n, 1, 1, wv_z, rw_double);
    CHECK_ERROR("ZCHSHX", 1);
    ctest_reset_state();
    qrupdate_zchshx(n, R_z, n, 0, 1, wv_z, rw_double);
    CHECK_ERROR("ZCHSHX", 4);
    ctest_reset_state();
    qrupdate_zchshx(n, R_z, n, 1, 0, wv_z, rw_double);
    CHECK_ERROR("ZCHSHX", 5);

    /* ====== LU rank-1 update ====== */
    ctest_reset_state();
    qrupdate_slu1up(-1, n, L_s, n, R_s, n, rhs_s, v_s);
    CHECK_ERROR("SLU1UP", 1);
    ctest_reset_state();
    qrupdate_slu1up(n, -1, L_s, n, R_s, n, rhs_s, v_s);
    CHECK_ERROR("SLU1UP", 2);
    ctest_reset_state();
    qrupdate_slu1up(n, n, L_s, n-1, R_s, n, rhs_s, v_s);
    CHECK_ERROR("SLU1UP", 4);
    ctest_reset_state();
    qrupdate_slu1up(n, n, L_s, n, R_s, n-1, rhs_s, v_s);
    CHECK_ERROR("SLU1UP", 6);
    ctest_reset_state();
    qrupdate_dlu1up(-1, n, L_d, n, R_d, n, rhs_d, v_d);
    CHECK_ERROR("DLU1UP", 1);
    ctest_reset_state();
    qrupdate_dlu1up(n, -1, L_d, n, R_d, n, rhs_d, v_d);
    CHECK_ERROR("DLU1UP", 2);
    ctest_reset_state();
    qrupdate_dlu1up(n, n, L_d, n-1, R_d, n, rhs_d, v_d);
    CHECK_ERROR("DLU1UP", 4);
    ctest_reset_state();
    qrupdate_dlu1up(n, n, L_d, n, R_d, n-1, rhs_d, v_d);
    CHECK_ERROR("DLU1UP", 6);
    ctest_reset_state();
    qrupdate_clu1up(-1, n, L_c, n, R_c, n, rhs_c, v_c);
    CHECK_ERROR("CLU1UP", 1);
    ctest_reset_state();
    qrupdate_clu1up(n, -1, L_c, n, R_c, n, rhs_c, v_c);
    CHECK_ERROR("CLU1UP", 2);
    ctest_reset_state();
    qrupdate_clu1up(n, n, L_c, n-1, R_c, n, rhs_c, v_c);
    CHECK_ERROR("CLU1UP", 4);
    ctest_reset_state();
    qrupdate_clu1up(n, n, L_c, n, R_c, n-1, rhs_c, v_c);
    CHECK_ERROR("CLU1UP", 6);
    ctest_reset_state();
    qrupdate_zlu1up(-1, n, L_z, n, R_z, n, rhs_z, v_z);
    CHECK_ERROR("ZLU1UP", 1);
    ctest_reset_state();
    qrupdate_zlu1up(n, -1, L_z, n, R_z, n, rhs_z, v_z);
    CHECK_ERROR("ZLU1UP", 2);
    ctest_reset_state();
    qrupdate_zlu1up(n, n, L_z, n-1, R_z, n, rhs_z, v_z);
    CHECK_ERROR("ZLU1UP", 4);
    ctest_reset_state();
    qrupdate_zlu1up(n, n, L_z, n, R_z, n-1, rhs_z, v_z);
    CHECK_ERROR("ZLU1UP", 6);

    /* ====== LU+perm rank-1 update ====== */
    ctest_reset_state();
    qrupdate_slup1up(-1, n, L_s, n, R_s, n, p_s, rhs_s, v_s, wv_s);
    CHECK_ERROR("SLUP1UP", 1);
    ctest_reset_state();
    qrupdate_slup1up(n, -1, L_s, n, R_s, n, p_s, rhs_s, v_s, wv_s);
    CHECK_ERROR("SLUP1UP", 2);
    ctest_reset_state();
    qrupdate_slup1up(n, n, L_s, n-1, R_s, n, p_s, rhs_s, v_s, wv_s);
    CHECK_ERROR("SLUP1UP", 4);
    ctest_reset_state();
    qrupdate_slup1up(n, n, L_s, n, R_s, n-1, p_s, rhs_s, v_s, wv_s);
    CHECK_ERROR("SLUP1UP", 6);
    ctest_reset_state();
    qrupdate_dlup1up(-1, n, L_d, n, R_d, n, p_d, rhs_d, v_d, wv_d);
    CHECK_ERROR("DLUP1UP", 1);
    ctest_reset_state();
    qrupdate_dlup1up(n, -1, L_d, n, R_d, n, p_d, rhs_d, v_d, wv_d);
    CHECK_ERROR("DLUP1UP", 2);
    ctest_reset_state();
    qrupdate_dlup1up(n, n, L_d, n-1, R_d, n, p_d, rhs_d, v_d, wv_d);
    CHECK_ERROR("DLUP1UP", 4);
    ctest_reset_state();
    qrupdate_dlup1up(n, n, L_d, n, R_d, n-1, p_d, rhs_d, v_d, wv_d);
    CHECK_ERROR("DLUP1UP", 6);
    ctest_reset_state();
    qrupdate_clup1up(-1, n, L_c, n, R_c, n, p_c_int, rhs_c, v_c, wv_c);
    CHECK_ERROR("CLUP1UP", 1);
    ctest_reset_state();
    qrupdate_clup1up(n, -1, L_c, n, R_c, n, p_c_int, rhs_c, v_c, wv_c);
    CHECK_ERROR("CLUP1UP", 2);
    ctest_reset_state();
    qrupdate_clup1up(n, n, L_c, n-1, R_c, n, p_c_int, rhs_c, v_c, wv_c);
    CHECK_ERROR("CLUP1UP", 4);
    ctest_reset_state();
    qrupdate_clup1up(n, n, L_c, n, R_c, n-1, p_c_int, rhs_c, v_c, wv_c);
    CHECK_ERROR("CLUP1UP", 6);
    ctest_reset_state();
    qrupdate_zlup1up(-1, n, L_z, n, R_z, n, p_z_int, rhs_z, v_z, wv_z);
    CHECK_ERROR("ZLUP1UP", 1);
    ctest_reset_state();
    qrupdate_zlup1up(n, -1, L_z, n, R_z, n, p_z_int, rhs_z, v_z, wv_z);
    CHECK_ERROR("ZLUP1UP", 2);
    ctest_reset_state();
    qrupdate_zlup1up(n, n, L_z, n-1, R_z, n, p_z_int, rhs_z, v_z, wv_z);
    CHECK_ERROR("ZLUP1UP", 4);
    ctest_reset_state();
    qrupdate_zlup1up(n, n, L_z, n, R_z, n-1, p_z_int, rhs_z, v_z, wv_z);
    CHECK_ERROR("ZLUP1UP", 6);

    /* ====== QR rank-1 update ====== */
    ctest_reset_state();
    qrupdate_sqr1up(-1, n, n, Q_s, n, R_s, n, rhs_s, v_s, wv_s);
    CHECK_ERROR("SQR1UP", 1);
    ctest_reset_state();
    qrupdate_sqr1up(n, -1, n, Q_s, n, R_s, n, rhs_s, v_s, wv_s);
    CHECK_ERROR("SQR1UP", 2);
    ctest_reset_state();
    qrupdate_sqr1up(n, n, 99, Q_s, n, R_s, n, rhs_s, v_s, wv_s);
    CHECK_ERROR("SQR1UP", 3);
    ctest_reset_state();
    qrupdate_sqr1up(n, n, n, Q_s, n-1, R_s, n, rhs_s, v_s, wv_s);
    CHECK_ERROR("SQR1UP", 5);
    ctest_reset_state();
    qrupdate_sqr1up(n, n, n, Q_s, n, R_s, n-1, rhs_s, v_s, wv_s);
    CHECK_ERROR("SQR1UP", 7);
    ctest_reset_state();
    qrupdate_dqr1up(-1, n, n, Q_d, n, R_d, n, rhs_d, v_d, wv_d);
    CHECK_ERROR("DQR1UP", 1);
    ctest_reset_state();
    qrupdate_dqr1up(n, -1, n, Q_d, n, R_d, n, rhs_d, v_d, wv_d);
    CHECK_ERROR("DQR1UP", 2);
    ctest_reset_state();
    qrupdate_dqr1up(n, n, 99, Q_d, n, R_d, n, rhs_d, v_d, wv_d);
    CHECK_ERROR("DQR1UP", 3);
    ctest_reset_state();
    qrupdate_dqr1up(n, n, n, Q_d, n-1, R_d, n, rhs_d, v_d, wv_d);
    CHECK_ERROR("DQR1UP", 5);
    ctest_reset_state();
    qrupdate_dqr1up(n, n, n, Q_d, n, R_d, n-1, rhs_d, v_d, wv_d);
    CHECK_ERROR("DQR1UP", 7);
    ctest_reset_state();
    qrupdate_cqr1up(-1, n, n, Q_c, n, R_c, n, rhs_c, v_c, wv_c, rw_float);
    CHECK_ERROR("CQR1UP", 1);
    ctest_reset_state();
    qrupdate_cqr1up(n, -1, n, Q_c, n, R_c, n, rhs_c, v_c, wv_c, rw_float);
    CHECK_ERROR("CQR1UP", 2);
    ctest_reset_state();
    qrupdate_cqr1up(n, n, 99, Q_c, n, R_c, n, rhs_c, v_c, wv_c, rw_float);
    CHECK_ERROR("CQR1UP", 3);
    ctest_reset_state();
    qrupdate_cqr1up(n, n, n, Q_c, n-1, R_c, n, rhs_c, v_c, wv_c, rw_float);
    CHECK_ERROR("CQR1UP", 5);
    ctest_reset_state();
    qrupdate_cqr1up(n, n, n, Q_c, n, R_c, n-1, rhs_c, v_c, wv_c, rw_float);
    CHECK_ERROR("CQR1UP", 7);
    ctest_reset_state();
    qrupdate_zqr1up(-1, n, n, Q_z, n, R_z, n, rhs_z, v_z, wv_z, rw_double);
    CHECK_ERROR("ZQR1UP", 1);
    ctest_reset_state();
    qrupdate_zqr1up(n, -1, n, Q_z, n, R_z, n, rhs_z, v_z, wv_z, rw_double);
    CHECK_ERROR("ZQR1UP", 2);
    ctest_reset_state();
    qrupdate_zqr1up(n, n, 99, Q_z, n, R_z, n, rhs_z, v_z, wv_z, rw_double);
    CHECK_ERROR("ZQR1UP", 3);
    ctest_reset_state();
    qrupdate_zqr1up(n, n, n, Q_z, n-1, R_z, n, rhs_z, v_z, wv_z, rw_double);
    CHECK_ERROR("ZQR1UP", 5);
    ctest_reset_state();
    qrupdate_zqr1up(n, n, n, Q_z, n, R_z, n-1, rhs_z, v_z, wv_z, rw_double);
    CHECK_ERROR("ZQR1UP", 7);

    /* ====== QR delete (column) ====== */
    ctest_reset_state();
    qrupdate_sqrdec(-1, n, n, Q_s, n, R_s, n, 1, w_s);
    CHECK_ERROR("SQRDEC", 1);
    ctest_reset_state();
    qrupdate_sqrdec(n, -1, n, Q_s, n, R_s, n, 1, w_s);
    CHECK_ERROR("SQRDEC", 2);
    ctest_reset_state();
    qrupdate_sqrdec(n, n, 99, Q_s, n, R_s, n, 1, w_s);
    CHECK_ERROR("SQRDEC", 3);
    ctest_reset_state();
    qrupdate_sqrdec(n, n, n, Q_s, n-1, R_s, n, 1, w_s);
    CHECK_ERROR("SQRDEC", 5);
    ctest_reset_state();
    qrupdate_sqrdec(n, n, n, Q_s, n, R_s, n-1, 1, w_s);
    CHECK_ERROR("SQRDEC", 7);
    ctest_reset_state();
    qrupdate_sqrdec(n, n, n, Q_s, n, R_s, n, 0, w_s);
    CHECK_ERROR("SQRDEC", 8);
    ctest_reset_state();
    qrupdate_dqrdec(-1, n, n, Q_d, n, R_d, n, 1, w_d);
    CHECK_ERROR("DQRDEC", 1);
    ctest_reset_state();
    qrupdate_dqrdec(n, -1, n, Q_d, n, R_d, n, 1, w_d);
    CHECK_ERROR("DQRDEC", 2);
    ctest_reset_state();
    qrupdate_dqrdec(n, n, 99, Q_d, n, R_d, n, 1, w_d);
    CHECK_ERROR("DQRDEC", 3);
    ctest_reset_state();
    qrupdate_dqrdec(n, n, n, Q_d, n-1, R_d, n, 1, w_d);
    CHECK_ERROR("DQRDEC", 5);
    ctest_reset_state();
    qrupdate_dqrdec(n, n, n, Q_d, n, R_d, n-1, 1, w_d);
    CHECK_ERROR("DQRDEC", 7);
    ctest_reset_state();
    qrupdate_dqrdec(n, n, n, Q_d, n, R_d, n, 0, w_d);
    CHECK_ERROR("DQRDEC", 8);
    ctest_reset_state();
    qrupdate_cqrdec(-1, n, n, Q_c, n, R_c, n, 1, rw_float);
    CHECK_ERROR("CQRDEC", 1);
    ctest_reset_state();
    qrupdate_cqrdec(n, -1, n, Q_c, n, R_c, n, 1, rw_float);
    CHECK_ERROR("CQRDEC", 2);
    ctest_reset_state();
    qrupdate_cqrdec(n, n, 99, Q_c, n, R_c, n, 1, rw_float);
    CHECK_ERROR("CQRDEC", 3);
    ctest_reset_state();
    qrupdate_cqrdec(n, n, n, Q_c, n-1, R_c, n, 1, rw_float);
    CHECK_ERROR("CQRDEC", 5);
    ctest_reset_state();
    qrupdate_cqrdec(n, n, n, Q_c, n, R_c, n-1, 1, rw_float);
    CHECK_ERROR("CQRDEC", 7);
    ctest_reset_state();
    qrupdate_cqrdec(n, n, n, Q_c, n, R_c, n, 0, rw_float);
    CHECK_ERROR("CQRDEC", 8);
    ctest_reset_state();
    qrupdate_zqrdec(-1, n, n, Q_z, n, R_z, n, 1, rw_double);
    CHECK_ERROR("ZQRDEC", 1);
    ctest_reset_state();
    qrupdate_zqrdec(n, -1, n, Q_z, n, R_z, n, 1, rw_double);
    CHECK_ERROR("ZQRDEC", 2);
    ctest_reset_state();
    qrupdate_zqrdec(n, n, 99, Q_z, n, R_z, n, 1, rw_double);
    CHECK_ERROR("ZQRDEC", 3);
    ctest_reset_state();
    qrupdate_zqrdec(n, n, n, Q_z, n-1, R_z, n, 1, rw_double);
    CHECK_ERROR("ZQRDEC", 5);
    ctest_reset_state();
    qrupdate_zqrdec(n, n, n, Q_z, n, R_z, n-1, 1, rw_double);
    CHECK_ERROR("ZQRDEC", 7);
    ctest_reset_state();
    qrupdate_zqrdec(n, n, n, Q_z, n, R_z, n, 0, rw_double);
    CHECK_ERROR("ZQRDEC", 8);

    /* ====== QR delete (row) ====== */
    ctest_reset_state();
    qrupdate_sqrder(0, n, Q_s, n, R_s, n, 1, w_s);
    CHECK_ERROR("SQRDER", 1);
    ctest_reset_state();
    qrupdate_sqrder(n, n, Q_s, n, R_s, n, 0, w_s);
    CHECK_ERROR("SQRDER", 7);
    ctest_reset_state();
    qrupdate_dqrder(0, n, Q_d, n, R_d, n, 1, w_d);
    CHECK_ERROR("DQRDER", 1);
    ctest_reset_state();
    qrupdate_dqrder(n, n, Q_d, n, R_d, n, 0, w_d);
    CHECK_ERROR("DQRDER", 7);
    ctest_reset_state();
    qrupdate_cqrder(0, n, Q_c, n, R_c, n, 1, wv_c, rw_float);
    CHECK_ERROR("CQRDER", 1);
    ctest_reset_state();
    qrupdate_cqrder(n, n, Q_c, n, R_c, n, 0, wv_c, rw_float);
    CHECK_ERROR("CQRDER", 7);
    ctest_reset_state();
    qrupdate_zqrder(0, n, Q_z, n, R_z, n, 1, wv_z, rw_double);
    CHECK_ERROR("ZQRDER", 1);
    ctest_reset_state();
    qrupdate_zqrder(n, n, Q_z, n, R_z, n, 0, wv_z, rw_double);
    CHECK_ERROR("ZQRDER", 7);

    /* ====== QR increment (column) ====== */
    ctest_reset_state();
    qrupdate_sqrinc(-1, n, n, Q_s, n, R_s, n, 1, x_s, w_s);
    CHECK_ERROR("SQRINC", 1);
    ctest_reset_state();
    qrupdate_sqrinc(n, -1, n, Q_s, n, R_s, n, 1, x_s, w_s);
    CHECK_ERROR("SQRINC", 2);
    ctest_reset_state();
    qrupdate_sqrinc(n, n, 99, Q_s, n, R_s, n, 1, x_s, w_s);
    CHECK_ERROR("SQRINC", 3);
    ctest_reset_state();
    qrupdate_sqrinc(n, n, n, Q_s, n-1, R_s, n, 1, x_s, w_s);
    CHECK_ERROR("SQRINC", 5);
    ctest_reset_state();
    qrupdate_sqrinc(n, n, n, Q_s, n, R_s, 0, 1, x_s, w_s);
    CHECK_ERROR("SQRINC", 7);
    ctest_reset_state();
    qrupdate_sqrinc(n, n, n, Q_s, n, R_s, n, 0, x_s, w_s);
    CHECK_ERROR("SQRINC", 8);
    ctest_reset_state();
    qrupdate_dqrinc(-1, n, n, Q_d, n, R_d, n, 1, x_d, w_d);
    CHECK_ERROR("DQRINC", 1);
    ctest_reset_state();
    qrupdate_dqrinc(n, -1, n, Q_d, n, R_d, n, 1, x_d, w_d);
    CHECK_ERROR("DQRINC", 2);
    ctest_reset_state();
    qrupdate_dqrinc(n, n, 99, Q_d, n, R_d, n, 1, x_d, w_d);
    CHECK_ERROR("DQRINC", 3);
    ctest_reset_state();
    qrupdate_dqrinc(n, n, n, Q_d, n-1, R_d, n, 1, x_d, w_d);
    CHECK_ERROR("DQRINC", 5);
    ctest_reset_state();
    qrupdate_dqrinc(n, n, n, Q_d, n, R_d, 0, 1, x_d, w_d);
    CHECK_ERROR("DQRINC", 7);
    ctest_reset_state();
    qrupdate_dqrinc(n, n, n, Q_d, n, R_d, n, 0, x_d, w_d);
    CHECK_ERROR("DQRINC", 8);
    ctest_reset_state();
    qrupdate_cqrinc(-1, n, n, Q_c, n, R_c, n, 1, x_c, rw_float);
    CHECK_ERROR("CQRINC", 1);
    ctest_reset_state();
    qrupdate_cqrinc(n, -1, n, Q_c, n, R_c, n, 1, x_c, rw_float);
    CHECK_ERROR("CQRINC", 2);
    ctest_reset_state();
    qrupdate_cqrinc(n, n, 99, Q_c, n, R_c, n, 1, x_c, rw_float);
    CHECK_ERROR("CQRINC", 3);
    ctest_reset_state();
    qrupdate_cqrinc(n, n, n, Q_c, n-1, R_c, n, 1, x_c, rw_float);
    CHECK_ERROR("CQRINC", 5);
    ctest_reset_state();
    qrupdate_cqrinc(n, n, n, Q_c, n, R_c, 0, 1, x_c, rw_float);
    CHECK_ERROR("CQRINC", 7);
    ctest_reset_state();
    qrupdate_cqrinc(n, n, n, Q_c, n, R_c, n, 0, x_c, rw_float);
    CHECK_ERROR("CQRINC", 8);
    ctest_reset_state();
    qrupdate_zqrinc(-1, n, n, Q_z, n, R_z, n, 1, x_z, rw_double);
    CHECK_ERROR("ZQRINC", 1);
    ctest_reset_state();
    qrupdate_zqrinc(n, -1, n, Q_z, n, R_z, n, 1, x_z, rw_double);
    CHECK_ERROR("ZQRINC", 2);
    ctest_reset_state();
    qrupdate_zqrinc(n, n, 99, Q_z, n, R_z, n, 1, x_z, rw_double);
    CHECK_ERROR("ZQRINC", 3);
    ctest_reset_state();
    qrupdate_zqrinc(n, n, n, Q_z, n-1, R_z, n, 1, x_z, rw_double);
    CHECK_ERROR("ZQRINC", 5);
    ctest_reset_state();
    qrupdate_zqrinc(n, n, n, Q_z, n, R_z, 0, 1, x_z, rw_double);
    CHECK_ERROR("ZQRINC", 7);
    ctest_reset_state();
    qrupdate_zqrinc(n, n, n, Q_z, n, R_z, n, 0, x_z, rw_double);
    CHECK_ERROR("ZQRINC", 8);

    /* ====== QR inner (row) ====== */
    ctest_reset_state();
    qrupdate_sqrinr(n, -1, Q_s, n, R_s, n, 1, x_s, w_s);
    CHECK_ERROR("SQRINR", 2);
    ctest_reset_state();
    qrupdate_sqrinr(n, n, Q_s, n, R_s, n, 0, x_s, w_s);
    CHECK_ERROR("SQRINR", 7);
    ctest_reset_state();
    qrupdate_dqrinr(n, -1, Q_d, n, R_d, n, 1, x_d, w_d);
    CHECK_ERROR("DQRINR", 2);
    ctest_reset_state();
    qrupdate_dqrinr(n, n, Q_d, n, R_d, n, 0, x_d, w_d);
    CHECK_ERROR("DQRINR", 7);
    ctest_reset_state();
    qrupdate_cqrinr(n, -1, Q_c, n, R_c, n, 1, x_c, rw_float);
    CHECK_ERROR("CQRINR", 2);
    ctest_reset_state();
    qrupdate_cqrinr(n, n, Q_c, n, R_c, n, 0, x_c, rw_float);
    CHECK_ERROR("CQRINR", 7);
    ctest_reset_state();
    qrupdate_zqrinr(n, -1, Q_z, n, R_z, n, 1, x_z, rw_double);
    CHECK_ERROR("ZQRINR", 2);
    ctest_reset_state();
    qrupdate_zqrinr(n, n, Q_z, n, R_z, n, 0, x_z, rw_double);
    CHECK_ERROR("ZQRINR", 7);

    /* ====== QR shift ====== */
    ctest_reset_state();
    qrupdate_sqrshc(-1, n, n, Q_s, n, R_s, n, 1, 1, w_s);
    CHECK_ERROR("SQRSHC", 1);
    ctest_reset_state();
    qrupdate_sqrshc(n, -1, n, Q_s, n, R_s, n, 1, 1, w_s);
    CHECK_ERROR("SQRSHC", 2);
    ctest_reset_state();
    qrupdate_sqrshc(n, n, 99, Q_s, n, R_s, n, 1, 1, w_s);
    CHECK_ERROR("SQRSHC", 3);
    ctest_reset_state();
    qrupdate_sqrshc(n, n, n, Q_s, n, R_s, n, 0, 1, w_s);
    CHECK_ERROR("SQRSHC", 6);
    ctest_reset_state();
    qrupdate_sqrshc(n, n, n, Q_s, n, R_s, n, 1, 0, w_s);
    CHECK_ERROR("SQRSHC", 7);
    ctest_reset_state();
    qrupdate_dqrshc(-1, n, n, Q_d, n, R_d, n, 1, 1, w_d);
    CHECK_ERROR("DQRSHC", 1);
    ctest_reset_state();
    qrupdate_dqrshc(n, -1, n, Q_d, n, R_d, n, 1, 1, w_d);
    CHECK_ERROR("DQRSHC", 2);
    ctest_reset_state();
    qrupdate_dqrshc(n, n, 99, Q_d, n, R_d, n, 1, 1, w_d);
    CHECK_ERROR("DQRSHC", 3);
    ctest_reset_state();
    qrupdate_dqrshc(n, n, n, Q_d, n, R_d, n, 0, 1, w_d);
    CHECK_ERROR("DQRSHC", 6);
    ctest_reset_state();
    qrupdate_dqrshc(n, n, n, Q_d, n, R_d, n, 1, 0, w_d);
    CHECK_ERROR("DQRSHC", 7);
    ctest_reset_state();
    qrupdate_cqrshc(-1, n, n, Q_c, n, R_c, n, 1, 1, wv_c, rw_float);
    CHECK_ERROR("CQRSHC", 1);
    ctest_reset_state();
    qrupdate_cqrshc(n, -1, n, Q_c, n, R_c, n, 1, 1, wv_c, rw_float);
    CHECK_ERROR("CQRSHC", 2);
    ctest_reset_state();
    qrupdate_cqrshc(n, n, 99, Q_c, n, R_c, n, 1, 1, wv_c, rw_float);
    CHECK_ERROR("CQRSHC", 3);
    ctest_reset_state();
    qrupdate_cqrshc(n, n, n, Q_c, n, R_c, n, 0, 1, wv_c, rw_float);
    CHECK_ERROR("CQRSHC", 6);
    ctest_reset_state();
    qrupdate_cqrshc(n, n, n, Q_c, n, R_c, n, 1, 0, wv_c, rw_float);
    CHECK_ERROR("CQRSHC", 7);
    ctest_reset_state();
    qrupdate_zqrshc(-1, n, n, Q_z, n, R_z, n, 1, 1, wv_z, rw_double);
    CHECK_ERROR("ZQRSHC", 1);
    ctest_reset_state();
    qrupdate_zqrshc(n, -1, n, Q_z, n, R_z, n, 1, 1, wv_z, rw_double);
    CHECK_ERROR("ZQRSHC", 2);
    ctest_reset_state();
    qrupdate_zqrshc(n, n, 99, Q_z, n, R_z, n, 1, 1, wv_z, rw_double);
    CHECK_ERROR("ZQRSHC", 3);
    ctest_reset_state();
    qrupdate_zqrshc(n, n, n, Q_z, n, R_z, n, 0, 1, wv_z, rw_double);
    CHECK_ERROR("ZQRSHC", 6);
    ctest_reset_state();
    qrupdate_zqrshc(n, n, n, Q_z, n, R_z, n, 1, 0, wv_z, rw_double);
    CHECK_ERROR("ZQRSHC", 7);

    /* ====== Givens rotations ====== */
    ctest_reset_state();
    dir = 'X';
    qrupdate_sqrot(&dir, n, n, Q_s, n, c_s, s_s);
    CHECK_ERROR("SQROT", 1);
    ctest_reset_state();
    dir = 'F';
    qrupdate_sqrot(&dir, -1, n, Q_s, n, c_s, s_s);
    CHECK_ERROR("SQROT", 2);
    ctest_reset_state();
    qrupdate_sqrot(&dir, n, -1, Q_s, n, c_s, s_s);
    CHECK_ERROR("SQROT", 3);
    ctest_reset_state();
    qrupdate_sqrot(&dir, n, n, Q_s, n-1, c_s, s_s);
    CHECK_ERROR("SQROT", 5);
    ctest_reset_state();
    dir = 'X';
    qrupdate_dqrot(&dir, n, n, Q_d, n, c_d, s_d);
    CHECK_ERROR("DQROT", 1);
    ctest_reset_state();
    dir = 'F';
    qrupdate_dqrot(&dir, -1, n, Q_d, n, c_d, s_d);
    CHECK_ERROR("DQROT", 2);
    ctest_reset_state();
    qrupdate_dqrot(&dir, n, -1, Q_d, n, c_d, s_d);
    CHECK_ERROR("DQROT", 3);
    ctest_reset_state();
    qrupdate_dqrot(&dir, n, n, Q_d, n-1, c_d, s_d);
    CHECK_ERROR("DQROT", 5);
    ctest_reset_state();
    dir = 'X';
    qrupdate_cqrot(&dir, n, n, Q_c, n, c_c, s_c);
    CHECK_ERROR("CQROT", 1);
    ctest_reset_state();
    dir = 'F';
    qrupdate_cqrot(&dir, -1, n, Q_c, n, c_c, s_c);
    CHECK_ERROR("CQROT", 2);
    ctest_reset_state();
    qrupdate_cqrot(&dir, n, -1, Q_c, n, c_c, s_c);
    CHECK_ERROR("CQROT", 3);
    ctest_reset_state();
    qrupdate_cqrot(&dir, n, n, Q_c, n-1, c_c, s_c);
    CHECK_ERROR("CQROT", 5);
    ctest_reset_state();
    dir = 'X';
    qrupdate_zqrot(&dir, n, n, Q_z, n, c_d, s_z);
    CHECK_ERROR("ZQROT", 1);
    ctest_reset_state();
    dir = 'F';
    qrupdate_zqrot(&dir, -1, n, Q_z, n, c_d, s_z);
    CHECK_ERROR("ZQROT", 2);
    ctest_reset_state();
    qrupdate_zqrot(&dir, n, -1, Q_z, n, c_d, s_z);
    CHECK_ERROR("ZQROT", 3);
    ctest_reset_state();
    qrupdate_zqrot(&dir, n, n, Q_z, n-1, c_d, s_z);
    CHECK_ERROR("ZQROT", 5);

    /* ====== QH factor ====== */
    ctest_reset_state();
    qrupdate_sqhqr(-1, n, R_s, n, c_s, s_s);
    CHECK_ERROR("SQHQR", 1);
    ctest_reset_state();
    qrupdate_sqhqr(n, -1, R_s, n, c_s, s_s);
    CHECK_ERROR("SQHQR", 2);
    ctest_reset_state();
    qrupdate_sqhqr(n, n, R_s, n-1, c_s, s_s);
    CHECK_ERROR("SQHQR", 4);
    ctest_reset_state();
    qrupdate_dqhqr(-1, n, R_d, n, c_d, s_d);
    CHECK_ERROR("DQHQR", 1);
    ctest_reset_state();
    qrupdate_dqhqr(n, -1, R_d, n, c_d, s_d);
    CHECK_ERROR("DQHQR", 2);
    ctest_reset_state();
    qrupdate_dqhqr(n, n, R_d, n-1, c_d, s_d);
    CHECK_ERROR("DQHQR", 4);
    ctest_reset_state();
    qrupdate_cqhqr(-1, n, R_c, n, c_c, s_c);
    CHECK_ERROR("CQHQR", 1);
    ctest_reset_state();
    qrupdate_cqhqr(n, -1, R_c, n, c_c, s_c);
    CHECK_ERROR("CQHQR", 2);
    ctest_reset_state();
    qrupdate_cqhqr(n, n, R_c, n-1, c_c, s_c);
    CHECK_ERROR("CQHQR", 4);
    ctest_reset_state();
    qrupdate_zqhqr(-1, n, R_z, n, c_d, s_z);
    CHECK_ERROR("ZQHQR", 1);
    ctest_reset_state();
    qrupdate_zqhqr(n, -1, R_z, n, c_d, s_z);
    CHECK_ERROR("ZQHQR", 2);
    ctest_reset_state();
    qrupdate_zqhqr(n, n, R_z, n-1, c_d, s_z);
    CHECK_ERROR("ZQHQR", 4);

    /* ====== QR-QH ====== */
    ctest_reset_state();
    qrupdate_sqrqh(-1, n, R_s, n, c_s, s_s);
    CHECK_ERROR("SQRQH", 1);
    ctest_reset_state();
    qrupdate_sqrqh(n, -1, R_s, n, c_s, s_s);
    CHECK_ERROR("SQRQH", 2);
    ctest_reset_state();
    qrupdate_sqrqh(n, n, R_s, n-1, c_s, s_s);
    CHECK_ERROR("SQRQH", 4);
    ctest_reset_state();
    qrupdate_dqrqh(-1, n, R_d, n, c_d, s_d);
    CHECK_ERROR("DQRQH", 1);
    ctest_reset_state();
    qrupdate_dqrqh(n, -1, R_d, n, c_d, s_d);
    CHECK_ERROR("DQRQH", 2);
    ctest_reset_state();
    qrupdate_dqrqh(n, n, R_d, n-1, c_d, s_d);
    CHECK_ERROR("DQRQH", 4);
    ctest_reset_state();
    qrupdate_cqrqh(-1, n, R_c, n, c_c, s_c);
    CHECK_ERROR("CQRQH", 1);
    ctest_reset_state();
    qrupdate_cqrqh(n, -1, R_c, n, c_c, s_c);
    CHECK_ERROR("CQRQH", 2);
    ctest_reset_state();
    qrupdate_cqrqh(n, n, R_c, n-1, c_c, s_c);
    CHECK_ERROR("CQRQH", 4);
    ctest_reset_state();
    qrupdate_zqrqh(-1, n, R_z, n, c_d, s_z);
    CHECK_ERROR("ZQRQH", 1);
    ctest_reset_state();
    qrupdate_zqrqh(n, -1, R_z, n, c_d, s_z);
    CHECK_ERROR("ZQRQH", 2);
    ctest_reset_state();
    qrupdate_zqrqh(n, n, R_z, n-1, c_d, s_z);
    CHECK_ERROR("ZQRQH", 4);

    /* ====== Givens Q vector ====== */
    ctest_reset_state();
    qrupdate_sgqvec(-1, n, Q_s, n, rhs_s);
    CHECK_ERROR("SGQVEC", 1);
    ctest_reset_state();
    qrupdate_sgqvec(n, -1, Q_s, n, rhs_s);
    CHECK_ERROR("SGQVEC", 2);
    ctest_reset_state();
    qrupdate_sgqvec(n, n, Q_s, n-1, rhs_s);
    CHECK_ERROR("SGQVEC", 4);
    ctest_reset_state();
    qrupdate_dgqvec(-1, n, Q_d, n, rhs_d);
    CHECK_ERROR("DGQVEC", 1);
    ctest_reset_state();
    qrupdate_dgqvec(n, -1, Q_d, n, rhs_d);
    CHECK_ERROR("DGQVEC", 2);
    ctest_reset_state();
    qrupdate_dgqvec(n, n, Q_d, n-1, rhs_d);
    CHECK_ERROR("DGQVEC", 4);
    ctest_reset_state();
    qrupdate_cgqvec(-1, n, Q_c, n, rhs_c);
    CHECK_ERROR("CGQVEC", 1);
    ctest_reset_state();
    qrupdate_cgqvec(n, -1, Q_c, n, rhs_c);
    CHECK_ERROR("CGQVEC", 2);
    ctest_reset_state();
    qrupdate_cgqvec(n, n, Q_c, n-1, rhs_c);
    CHECK_ERROR("CGQVEC", 4);
    ctest_reset_state();
    qrupdate_zgqvec(-1, n, Q_z, n, rhs_z);
    CHECK_ERROR("ZGQVEC", 1);
    ctest_reset_state();
    qrupdate_zgqvec(n, -1, Q_z, n, rhs_z);
    CHECK_ERROR("ZGQVEC", 2);
    ctest_reset_state();
    qrupdate_zgqvec(n, n, Q_z, n-1, rhs_z);
    CHECK_ERROR("ZGQVEC", 4);

    if (fails == 0) {
        printf("All validation tests passed!\n");
    } else {
        printf("FAILED: %d test(s) failed\n", fails);
        return 1;
    }

    return 0;
}
